### ISSUE TITLE
Additional Model Information

### ISSUE THREAD

**Issue by dhulihan** [hulihanapplications/fletcher#9]
I'd like to be able to retrieve useful information about each model. This information should at least include the company's title and url. We may not be able to dynamically render the company title based on the model's class name since the properly formatted title can't always be derived correctly. In this case we could use I18n with each model's hash keyed with `[Model].name.underscore`.

Here's what the translation file could look like:

``` yaml
en:
  fletcher:
    models:
      amazon:
        title: "Amazon"
        url: "http://www.amazon.com"
      gamecouk:
        title: "Game.co.uk"
        url: "http://www.game.co.uk"
```

Here's an API example:

``` rb
I18n.locale = "en-US"
Fletcher.models.first.title # => "Amazon"
Fletcher.models.first.url # => "http://www.amazon.com"

I18n.locale = "en-GB"
Fletcher.models.first.url # => "http://www.amazon.co.uk"
```
